import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faUser, faBell, faGrip, faCompass, faLocationDot, faGear } from '@fortawesome/free-solid-svg-icons';
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <div className="app-container">
     <div className="weather-app">
      <div className="nav">
        <ul>
          <li><Link href=""><FontAwesomeIcon icon={faUser} /></Link></li>
          <li><Link href=""><FontAwesomeIcon icon={faBell} /></Link></li>
          <li><Link href="/"><FontAwesomeIcon icon={faGrip} /></Link></li>
          <li><Link href=""><FontAwesomeIcon icon={faCompass} /></Link></li>
          <li><Link href=""><FontAwesomeIcon icon={faLocationDot} /></Link></li>
          <li><Link href=""><FontAwesomeIcon icon={faGear} /></Link></li>
        </ul>
      </div>
      <div className="contents">
        {children}
        </div>

        
     </div>
    </div>
      </body>
    </html>
  );
}
